// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Account
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public string Address { get; set; }

    public string School { get; set; }

    public string Phone { get; set; }

    public string AvatarUrl { get; set; }

    public string Role { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<PayoutAccount> PayoutAccounts { get; set; } = new List<PayoutAccount>();

    public virtual ICollection<Pledge> Pledges { get; set; } = new List<Pledge>();

    public virtual ICollection<ProjectApproval> ProjectApprovals { get; set; } = new List<ProjectApproval>();

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    public virtual ICollection<SiteDonation> SiteDonations { get; set; } = new List<SiteDonation>();
}