// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Payment
{
    public Guid Id { get; set; }

    public string Provider { get; set; }

    public string Currency { get; set; }

    public decimal Amount { get; set; }

    public string ExternalId { get; set; }

    public string Status { get; set; }

    public DateTime? PaidAt { get; set; }

    public string RawJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Pledge> Pledges { get; set; } = new List<Pledge>();

    public virtual ICollection<SiteDonation> SiteDonations { get; set; } = new List<SiteDonation>();
}