// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class PayoutAccount
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string Provider { get; set; }

    public string AccountNumber { get; set; }

    public string AccountName { get; set; }

    public string BankName { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Account User { get; set; }
}