// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Pledge
{
    public Guid Id { get; set; }

    public Guid ProjectId { get; set; }

    public Guid? RewardTierId { get; set; }

    public Guid BackerId { get; set; }

    public decimal Amount { get; set; }

    public Guid PaymentId { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Account Backer { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual Project Project { get; set; }

    public virtual RewardTier RewardTier { get; set; }
}