// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ProjectApproval
{
    public Guid Id { get; set; }

    public Guid ProjectId { get; set; }

    public Guid AdminId { get; set; }

    public string Decision { get; set; }

    public string Note { get; set; }

    public DateTime DecidedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Account Admin { get; set; }

    public virtual Project Project { get; set; }
}