// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class RewardTier
{
    public Guid Id { get; set; }

    public Guid ProjectId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public decimal Amount { get; set; }

    public int? Quantity { get; set; }

    public DateOnly? DeliveryDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Pledge> Pledges { get; set; } = new List<Pledge>();

    public virtual Project Project { get; set; }
}