// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class SiteDonation
{
    public Guid Id { get; set; }

    public Guid? DonorId { get; set; }

    public decimal Amount { get; set; }

    public Guid PaymentId { get; set; }

    public string Status { get; set; }

    public string Message { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Account Donor { get; set; }

    public virtual Payment Payment { get; set; }
}